// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.games.relations;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.games.lookups;

public partial class Etiqueta
{
    public int IdEtiqueta { get; set; }

    public string Etiqueta1 { get; set; }

    public virtual ICollection<JuegosEtiqueta> JuegosEtiqueta { get; set; } = new List<JuegosEtiqueta>();
}