// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.core;
using DigitalStoreModel.Models.geography;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.games;

public partial class Desarrolladora
{
    public int IdDesarrolladora { get; set; }

    public string Nombre { get; set; }

    public string EmailContacto { get; set; }

    public int IdPais { get; set; }

    public string SitioWeb { get; set; }

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual ICollection<Juego> IdJuegos { get; set; } = new List<Juego>();
}