// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.core;
using DigitalStoreModel.Models.users.relations;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.games;

public partial class Logro
{
    public int IdLogro { get; set; }

    public int IdJuego { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public virtual Juego IdJuegoNavigation { get; set; }

    public virtual ICollection<UsuariosLogro> UsuariosLogros { get; set; } = new List<UsuariosLogro>();
}