// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.core;

namespace DigitalStoreModel.Models.games;

public partial class Pegi
{
    public int IdPegi { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Dlc> Dlcs { get; set; } = new List<Dlc>();

    public virtual ICollection<Juego> Juegos { get; set; } = new List<Juego>();
}