// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.core;

namespace DigitalStoreModel.Models.users;

public partial class Biblioteca
{
    public int IdBiblioteca { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();

    public virtual ICollection<Juego> IdJuegos { get; set; } = new List<Juego>();
}