// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.commerce;
using DigitalStoreModel.Models.core;

namespace DigitalStoreModel.Models.users;

public partial class DatosPagosGuardado
{
    public int IdMetodoPagoGuardado { get; set; }

    public int IdUsuario { get; set; }

    public string NumTarjeta { get; set; }

    public int IdFormaPago { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<Transaccion> Transacciones { get; set; } = new List<Transaccion>();
}