// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.commerce;
using DigitalStoreModel.Models.core;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.commerce.relations;

public partial class DescuentosProducto
{
    public int IdDescuentoProducto { get; set; }

    public int IdDescuento { get; set; }

    public int IdProducto { get; set; }

    public decimal Porcentaje { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public virtual ICollection<DetallesTransaccion> DetallesTransacciones { get; set; } = new List<DetallesTransaccion>();

    public virtual Descuento IdDescuentoNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }
}