// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.games;
using DigitalStoreModel.Models.users;

namespace DigitalStoreModel.Models.core
    ;

public partial class Dlc
{
    public int IdDlc { get; set; }

    public int IdJuego { get; set; }

    public string Descripcion { get; set; }

    public string Estado { get; set; }

    public DateOnly? FechaLanzamiento { get; set; }

    public int IdPegi { get; set; }

    public virtual Juego IdJuegoNavigation { get; set; }

    public virtual Pegi IdPegiNavigation { get; set; }

    public virtual ICollection<Producto> Productos { get; set; } = new List<Producto>();

    public virtual ICollection<Wishlist> IdWishlists { get; set; } = new List<Wishlist>();
}