// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.games;
using DigitalStoreModel.Models.games.lookups;
using DigitalStoreModel.Models.games.relations;
using DigitalStoreModel.Models.users;
using DigitalStoreModel.Models.users.relations;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.core;

public partial class Juego
{
    public int IdJuego { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public DateOnly? FechaLanzamiento { get; set; }

    public int IdPegi { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Dlc> Dlcs { get; set; } = new List<Dlc>();

    public virtual Pegi IdPegiNavigation { get; set; }

    public virtual ICollection<JuegosEtiqueta> JuegosEtiqueta { get; set; } = new List<JuegosEtiqueta>();

    public virtual ICollection<Logro> Logros { get; set; } = new List<Logro>();

    public virtual ICollection<Producto> Productos { get; set; } = new List<Producto>();

    public virtual ICollection<UsuariosJuego> UsuariosJuegos { get; set; } = new List<UsuariosJuego>();

    public virtual ICollection<Biblioteca> IdBibliotecas { get; set; } = new List<Biblioteca>();

    public virtual ICollection<Desarrolladora> IdDesarrolladoras { get; set; } = new List<Desarrolladora>();

    public virtual ICollection<Genero> IdGeneros { get; set; } = new List<Genero>();

    public virtual ICollection<Publisher> IdPublishers { get; set; } = new List<Publisher>();

    public virtual ICollection<SistemasOperativo> IdSistemaOperativos { get; set; } = new List<SistemasOperativo>();

    public virtual ICollection<Wishlist> IdWishlists { get; set; } = new List<Wishlist>();
}