// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.commerce;
using DigitalStoreModel.Models.commerce.relations;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.core;

public partial class Producto
{
    public int IdProducto { get; set; }

    public int? IdJuego { get; set; }

    public int? IdDlc { get; set; }

    public string Tipo { get; set; }

    public virtual ICollection<DescuentosProducto> DescuentosProductos { get; set; } = new List<DescuentosProducto>();

    public virtual ICollection<DetallesTransaccion> DetallesTransacciones { get; set; } = new List<DetallesTransaccion>();

    public virtual Dlc IdDlcNavigation { get; set; }

    public virtual Juego IdJuegoNavigation { get; set; }

    public virtual ICollection<PreciosProducto> PreciosProductos { get; set; } = new List<PreciosProducto>();
}