// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.commerce;
using DigitalStoreModel.Models.users;
using DigitalStoreModel.Models.users.relations;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.core;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string NombreUsuario { get; set; }

    public string Email { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public DateOnly FechaNac { get; set; }

    public DateOnly FechaRegistro { get; set; }

    public int IdBiblioteca { get; set; }

    public int IdWishlist { get; set; }

    public virtual ICollection<DatosPagosGuardado> DatosPagosGuardados { get; set; } = new List<DatosPagosGuardado>();

    public virtual Biblioteca IdBibliotecaNavigation { get; set; }

    public virtual Wishlist IdWishlistNavigation { get; set; }

    public virtual ICollection<Transaccion> Transacciones { get; set; } = new List<Transaccion>();

    public virtual ICollection<UsuariosJuego> UsuariosJuegos { get; set; } = new List<UsuariosJuego>();

    public virtual ICollection<UsuariosLogro> UsuariosLogros { get; set; } = new List<UsuariosLogro>();
}