// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.geography;

public partial class Calle
{
    public int IdCalle { get; set; }

    public string Calle1 { get; set; }

    public int IdProv { get; set; }

    public virtual ICollection<Direccion> Direcciones { get; set; } = new List<Direccion>();

    public virtual Provincia IdProvNavigation { get; set; }
}