// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.geography;

public partial class Direccion
{
    public int IdDireccion { get; set; }

    public int IdCalle { get; set; }

    public int Numero { get; set; }

    public string CodigoPostal { get; set; }

    public virtual Calle IdCalleNavigation { get; set; }
}