// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.games;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.geography;

public partial class Pais
{
    public int IdPais { get; set; }

    public string Nombre { get; set; }

    public int IdRegion { get; set; }

    public virtual ICollection<Desarrolladora> Desarrolladoras { get; set; } = new List<Desarrolladora>();

    public virtual Region IdRegionNavigation { get; set; }

    public virtual ICollection<Provincia> Provincia { get; set; } = new List<Provincia>();

    public virtual ICollection<Publisher> Publishers { get; set; } = new List<Publisher>();
}