// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.geography;

public partial class Provincia
{
    public int IdProv { get; set; }

    public string Nombre { get; set; }

    public int IdPais { get; set; }

    public virtual ICollection<Calle> Calles { get; set; } = new List<Calle>();

    public virtual Pais IdPaisNavigation { get; set; }
}