// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.geography;

public partial class Region
{
    public int IdRegion { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Pais> Paises { get; set; } = new List<Pais>();
}