// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.commerce.relations;

namespace DigitalStoreModel.Models.commerce;

public partial class Descuento
{
    public int IdDescuento { get; set; }

    public string Nombre { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public virtual ICollection<DescuentosProducto> DescuentosProductos { get; set; } = new List<DescuentosProducto>();
}