// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.commerce.relations;
using DigitalStoreModel.Models.core;
using System;
using System.Collections.Generic;


namespace DigitalStoreModel.Models.commerce;

public partial class DetallesTransaccion
{
    public int IdDetalleTransaccion { get; set; }

    public int IdTransaccion { get; set; }

    public int IdProducto { get; set; }

    public int? IdDescuentoProducto { get; set; }

    public int IdPrecioProducto { get; set; }

    public virtual DescuentosProducto IdDescuentoProductoNavigation { get; set; }

    public virtual PreciosProducto IdPrecioProductoNavigation { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual Transaccion IdTransaccionNavigation { get; set; }
}