// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.users;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.commerce;

public partial class FormasPago
{
    public int IdFormaPago { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<DatosPagosGuardado> DatosPagosGuardados { get; set; } = new List<DatosPagosGuardado>();
}