// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.core;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.commerce;

public partial class PreciosProducto
{
    public int IdPrecioProducto { get; set; }

    public int IdProducto { get; set; }

    public decimal Precio { get; set; }

    public DateOnly FechaInicio { get; set; }

    public virtual ICollection<DetallesTransaccion> DetallesTransacciones { get; set; } = new List<DetallesTransaccion>();

    public virtual Producto IdProductoNavigation { get; set; }
}