// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.core;
using DigitalStoreModel.Models.users;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.commerce;

public partial class Transaccion
{
    public int IdTransaccion { get; set; }

    public int IdUsuario { get; set; }

    public DateOnly Fecha { get; set; }

    public string Tipo { get; set; }

    public int IdMetodoPagoGuardado { get; set; }

    public virtual ICollection<DetallesTransaccion> DetallesTransacciones { get; set; } = new List<DetallesTransaccion>();

    public virtual DatosPagosGuardado IdMetodoPagoGuardadoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}