// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DigitalStoreModel.Models.core;
using DigitalStoreModel.Models.games.lookups;
using System;
using System.Collections.Generic;

namespace DigitalStoreModel.Models.games.relations;

public partial class JuegosEtiqueta
{
    public int IdEtiqueta { get; set; }

    public int IdJuego { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public virtual Etiqueta IdEtiquetaNavigation { get; set; }

    public virtual Juego IdJuegoNavigation { get; set; }
}