// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.core;

namespace DigitalStoreModel.Models.users.relations;

public partial class UsuariosJuego
{
    public int IdUsuarioJuego { get; set; }

    public int IdUsuario { get; set; }

    public int IdJuego { get; set; }

    public int? TiempoTotal { get; set; }

    public DateOnly? FechaAdquisicion { get; set; }

    public DateTime? UltimaVez { get; set; }

    public virtual Juego IdJuegoNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}