// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DigitalStoreModel.Models.core;
using DigitalStoreModel.Models.games;

namespace DigitalStoreModel.Models.users.relations;

public partial class UsuariosLogro
{
    public int IdUsuarioLogros { get; set; }

    public int IdUsuario { get; set; }

    public int IdLogro { get; set; }

    public DateTime? FechaDesbloqueo { get; set; }

    public virtual Logro IdLogroNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}